### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by nygrenh** [rage/mooc.fi#442]
```
          resources:
            limits:
              memory: 1500Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 100m
```
